apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spring-boot-camel-xml
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-boot-camel-xml
    app.kubernetes.io/part-of: spring-boot-camel-xml
  name: spring-boot-camel-xml8gz8
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spring-boot-camel-xml
    weight: null
status: {}
